In [1]:
import os, csv, pandas as pd

In [2]:
sumlev_names={'010':'US','020':'Region','030':'Division','040':'State','050':'County',
             '060':'County Subdiv','140':'Tract','150':'Blk Group','160':'Place','170':'Cons City',
              '250':'Tribal Area','251':'Tribal Subdiv','256':'Tribal Tract','258':'Tribal Blk Group', 
              '310':'CBSA','400':'Urban Area','500':'Cong Dist','795':'PUMA','860':'ZCTA'}

In [3]:
geo_names={}
name_file=os.path.join('metatables','acs_geos.csv')
with open(name_file, 'r', newline='') as csvfile:
    reader = csv.DictReader(csvfile)
    for row in reader:
        geo_names[row['geoid']]=row['geoname']
len(geo_names)

405898

# Significant Difference

In [4]:
geo_file=os.path.join('geosd_count.json')
geo_sd=pd.read_json(geo_file,orient='index')
geo_sd['geoname']=geo_sd.index.map(geo_names)
geo_sd['sumlevel']=geo_sd.index.str.slice(0, 3)
geo_sd['sumlevel']=geo_sd['sumlevel'].map(sumlev_names)
geo_sd.sort_values(by='true_pct',ascending=False)

,true,false,null,true_pct,false_pct,null_pct,geoname,sumlevel
02000US4,303,15,0,95.3,4.7,0.0,West Region,Region
03000US5,302,16,0,95.0,5.0,0.0,South Atlantic Division,Division
01000US,299,19,0,94.0,6.0,0.0,United States,US
02000US3,296,22,0,93.1,6.9,0.0,South Region,Region
06000US4715790158,294,24,0,92.5,7.5,0.0,"District 1, Shelby County, Tennessee",County Subdiv
...,...,...,...,...,...,...,...,...
14000US17031980100,0,308,10,0.0,96.9,3.1,"Census Tract 9801, Cook County, Illinois",Tract
14000US17031980000,0,308,10,0.0,96.9,3.1,"Census Tract 9800, Cook County, Illinois",Tract
15000US360610084001,0,227,91,0.0,71.4,28.6,"Block Group 1, Census Tract 84, New York Count...",Blk Group
15000US360610086010,0,227,91,0.0,71.4,28.6,"Block Group 0, Census Tract 86.01, New York Co...",Blk Group
86000US04855,0,316,2,0.0,99.4,0.6,ZCTA5 04855,ZCTA

In [5]:
geocount=len(geo_sd)
geocount

405787

In [6]:
sum_geotrue=geo_sd['true'].sum()
sum_geotrue

11648350

In [7]:
min_true = geo_sd['true'].min()
max_true = geo_sd['true'].max()
mean_true = round(geo_sd['true'].mean(),0)
std_true=round(geo_sd['true'].std(),0)
med_true = geo_sd['true'].median()
mode_true = geo_sd['true'].mode().iloc[0] 
print(min_true,max_true,mean_true,std_true,med_true,mode_true)

0 303 29.0 23.0 23.0 15

In [8]:
bins = [-1, 0, 24.9, 49.9, 74.9, 100]
labels=['0','0.1 to 24.9', '25 to 49.9', '50 to 74.9', '75 to 100']
geo_sd['true_bin']=pd.cut(geo_sd['true_pct'],bins=bins,labels=labels,include_lowest=True)
geo_sd.sort_values(by='true_pct',ascending=False)

,true,false,null,true_pct,false_pct,null_pct,geoname,sumlevel,true_bin
02000US4,303,15,0,95.3,4.7,0.0,West Region,Region,75 to 100
03000US5,302,16,0,95.0,5.0,0.0,South Atlantic Division,Division,75 to 100
01000US,299,19,0,94.0,6.0,0.0,United States,US,75 to 100
02000US3,296,22,0,93.1,6.9,0.0,South Region,Region,75 to 100
06000US4715790158,294,24,0,92.5,7.5,0.0,"District 1, Shelby County, Tennessee",County Subdiv,75 to 100
...,...,...,...,...,...,...,...,...,...
14000US17031980100,0,308,10,0.0,96.9,3.1,"Census Tract 9801, Cook County, Illinois",Tract,0
14000US17031980000,0,308,10,0.0,96.9,3.1,"Census Tract 9800, Cook County, Illinois",Tract,0
15000US360610084001,0,227,91,0.0,71.4,28.6,"Block Group 1, Census Tract 84, New York Count...",Blk Group,0
15000US360610086010,0,227,91,0.0,71.4,28.6,"Block Group 0, Census Tract 86.01, New York Co...",Blk Group,0
86000US04855,0,316,2,0.0,99.4,0.6,ZCTA5 04855,ZCTA,0

In [40]:
#counties_sd=geo_sd.loc[geo_sd['sumlevel']=='County']
#counties_sd.to_csv('county_counts_sd.csv')
#tracts_sd=geo_sd.loc[geo_sd['sumlevel']=='Tract']
#tracts_sd.to_csv('tracts_counts_sd.csv')

In [9]:
cnt_geotrue_bins=geo_sd.groupby('true_bin',observed=True)['true'].count().reset_index()
cnt_geotrue_bins['pct']=round((cnt_geotrue_bins['true']/geocount)*100,1)
cnt_geotrue_bins

      true_bin    true   pct
0            0    4550   1.1
1  0.1 to 24.9  386962  95.4
2   25 to 49.9   13129   3.2
3   50 to 74.9    1060   0.3
4    75 to 100      86   0.0

In [10]:
geo_sd.loc[geo_sd['true_bin']=='75 to 100',['true','true_pct','geoname']].sort_values(by='true_pct', ascending=False).head(n=47)

,true,true_pct,geoname
02000US4,303,95.3,West Region
03000US5,302,95.0,South Atlantic Division
01000US,299,94.0,United States
02000US3,296,93.1,South Region
03000US8,294,92.5,Mountain Division
06000US4715790158,294,92.5,"District 1, Shelby County, Tennessee"
04000US06,292,91.8,California
02000US2,291,91.5,Midwest Region
03000US7,289,90.9,West South Central Division
03000US9,289,90.9,Pacific Division
04000US48,287,90.3,Texas
03000US3,285,89.6,East North Central Division
06000US4715790728,285,89.6,"District 4, Shelby County, Tennessee"
02000US1,284,89.3,Northeast Region
31000US31080,284,89.3,"Los Angeles-Long Beach-Anaheim, CA Metro Area"
03000US2,283,89.0,Middle Atlantic Division
40000US51445,280,88.1,"Los Angeles--Long Beach--Anaheim, CA Urbanized..."
04000US12,279,87.7,Florida
04000US13,278,87.4,Georgia
05000US06037,273,85.8,"Los Angeles County, California"
04000US36,273,85.8,New York
40000US63217,271,85.2,"New York--Newark, NY--NJ--CT Urbanized Area (2..."
03000US1,270,84.9,New England Division
04000US42,269,84.6,Pennsylvania
03000US4,269,84.6,West North Central Division
06000US4715790348,268,84.3,"District 2, Shelby County, Tennessee"
04000US04,267,84.0,Arizona
04000US37,267,84.0,North Carolina
16000US3651000,267,84.0,"New York city, New York"
04000US53,266,83.6,Washington
03000US6,265,83.3,East South Central Division
06000US4715790538,262,82.4,"District 3, Shelby County, Tennessee"
04000US26,261,82.1,Michigan
04000US45,261,82.1,South Carolina
04000US47,261,82.1,Tennessee
04000US49,260,81.8,Utah
04000US08,258,81.1,Colorado
04000US17,258,81.1,Illinois
31000US41860,257,80.8,"San Francisco-Oakland-Berkeley, CA Metro Area"
31000US38060,257,80.8,"Phoenix-Mesa-Chandler, AZ Metro Area"
31000US42660,256,80.5,"Seattle-Tacoma-Bellevue, WA Metro Area"
05000US04013,256,80.5,"Maricopa County, Arizona"
05000US17031,255,80.2,"Cook County, Illinois"
06000US0401392601,255,80.2,"Phoenix CCD, Maricopa County, Arizona"
04000US32,254,79.9,Nevada
04000US39,254,79.9,Ohio
31000US16980,253,79.6,"Chicago-Naperville-Elgin, IL-IN-WI Metro Area"

In [11]:
cnt_sumlevs=geo_sd.groupby(['true_bin','sumlevel'],observed=True)['true'].count().reset_index()
cnt_sumlevs.sort_values(by=['true_bin','true'],ascending=False)

       true_bin          sumlevel    true
56    75 to 100             State      26
50    75 to 100              CBSA      18
58    75 to 100        Urban Area      13
53    75 to 100          Division       9
51    75 to 100            County       8
52    75 to 100     County Subdiv       5
55    75 to 100            Region       4
54    75 to 100             Place       2
57    75 to 100                US       1
39   50 to 74.9         Cong Dist     303
41   50 to 74.9            County     227
42   50 to 74.9     County Subdiv     124
38   50 to 74.9              CBSA     103
43   50 to 74.9              PUMA      93
48   50 to 74.9        Urban Area      83
44   50 to 74.9             Place      77
45   50 to 74.9             State      25
49   50 to 74.9              ZCTA      13
46   50 to 74.9             Tract       7
40   50 to 74.9         Cons City       3
47   50 to 74.9       Tribal Area       2
37   25 to 49.9              ZCTA    2812
29   25 to 49.9              PUMA    2195
32   25 to 49.9             Tract    2049
28   25 to 49.9     County Subdiv    1636
27   25 to 49.9            County    1614
30   25 to 49.9             Place    1475
24   25 to 49.9              CBSA     560
36   25 to 49.9        Urban Area     451
23   25 to 49.9         Blk Group     195
25   25 to 49.9         Cong Dist      65
33   25 to 49.9       Tribal Area      37
35   25 to 49.9      Tribal Tract      22
34   25 to 49.9     Tribal Subdiv      13
26   25 to 49.9         Cons City       4
31   25 to 49.9             State       1
9   0.1 to 24.9         Blk Group  218821
16  0.1 to 24.9             Tract   71194
13  0.1 to 24.9     County Subdiv   33576
22  0.1 to 24.9              ZCTA   29532
15  0.1 to 24.9             Place   27041
21  0.1 to 24.9        Urban Area    3045
12  0.1 to 24.9            County    1371
18  0.1 to 24.9  Tribal Blk Group     843
17  0.1 to 24.9       Tribal Area     531
19  0.1 to 24.9     Tribal Subdiv     406
20  0.1 to 24.9      Tribal Tract     396
10  0.1 to 24.9              CBSA     115
14  0.1 to 24.9              PUMA      90
11  0.1 to 24.9         Cons City       1
1             0     County Subdiv    1203
0             0         Blk Group     958
2             0             Place     915
8             0              ZCTA     763
3             0             Tract     392
4             0       Tribal Area     123
5             0  Tribal Blk Group      72
7             0      Tribal Tract      63
6             0     Tribal Subdiv      61

In [12]:
cnt_sumlevs['pct_group']=round((cnt_sumlevs['true']/cnt_sumlevs.groupby(
    ['true_bin'],observed=True)['true'].transform('sum'))*100,1)
cnt_sumlevs.sort_values(by=['true_bin','pct_group','true'],ascending=False)

       true_bin          sumlevel    true  pct_group
56    75 to 100             State      26       30.2
50    75 to 100              CBSA      18       20.9
58    75 to 100        Urban Area      13       15.1
53    75 to 100          Division       9       10.5
51    75 to 100            County       8        9.3
52    75 to 100     County Subdiv       5        5.8
55    75 to 100            Region       4        4.7
54    75 to 100             Place       2        2.3
57    75 to 100                US       1        1.2
39   50 to 74.9         Cong Dist     303       28.6
41   50 to 74.9            County     227       21.4
42   50 to 74.9     County Subdiv     124       11.7
38   50 to 74.9              CBSA     103        9.7
43   50 to 74.9              PUMA      93        8.8
48   50 to 74.9        Urban Area      83        7.8
44   50 to 74.9             Place      77        7.3
45   50 to 74.9             State      25        2.4
49   50 to 74.9              ZCTA      13        1.2
46   50 to 74.9             Tract       7        0.7
40   50 to 74.9         Cons City       3        0.3
47   50 to 74.9       Tribal Area       2        0.2
37   25 to 49.9              ZCTA    2812       21.4
29   25 to 49.9              PUMA    2195       16.7
32   25 to 49.9             Tract    2049       15.6
28   25 to 49.9     County Subdiv    1636       12.5
27   25 to 49.9            County    1614       12.3
30   25 to 49.9             Place    1475       11.2
24   25 to 49.9              CBSA     560        4.3
36   25 to 49.9        Urban Area     451        3.4
23   25 to 49.9         Blk Group     195        1.5
25   25 to 49.9         Cong Dist      65        0.5
33   25 to 49.9       Tribal Area      37        0.3
35   25 to 49.9      Tribal Tract      22        0.2
34   25 to 49.9     Tribal Subdiv      13        0.1
26   25 to 49.9         Cons City       4        0.0
31   25 to 49.9             State       1        0.0
9   0.1 to 24.9         Blk Group  218821       56.5
16  0.1 to 24.9             Tract   71194       18.4
13  0.1 to 24.9     County Subdiv   33576        8.7
22  0.1 to 24.9              ZCTA   29532        7.6
15  0.1 to 24.9             Place   27041        7.0
21  0.1 to 24.9        Urban Area    3045        0.8
12  0.1 to 24.9            County    1371        0.4
18  0.1 to 24.9  Tribal Blk Group     843        0.2
17  0.1 to 24.9       Tribal Area     531        0.1
19  0.1 to 24.9     Tribal Subdiv     406        0.1
20  0.1 to 24.9      Tribal Tract     396        0.1
10  0.1 to 24.9              CBSA     115        0.0
14  0.1 to 24.9              PUMA      90        0.0
11  0.1 to 24.9         Cons City       1        0.0
1             0     County Subdiv    1203       26.4
0             0         Blk Group     958       21.1
2             0             Place     915       20.1
8             0              ZCTA     763       16.8
3             0             Tract     392        8.6
4             0       Tribal Area     123        2.7
5             0  Tribal Blk Group      72        1.6
7             0      Tribal Tract      63        1.4
6             0     Tribal Subdiv      61        1.3

# CV

In [13]:
geo_file_cv=os.path.join('geocv_count.json')
geo_cv=pd.read_json(geo_file_cv,orient='index')
geo_cv['medhigh']=geo_cv['medium']+geo_cv['high']
geo_cv['medhigh_pct']=geo_cv['medium_pct']+geo_cv['high_pct']
geo_cv['geoname']=geo_cv.index.map(geo_names)
geo_cv['sumlevel']=geo_cv.index.str.slice(0, 3)
geo_cv['sumlevel']=geo_cv['sumlevel'].map(sumlev_names)
geo_cv.sort_values(by='medhigh',ascending=False)

,low,medium,high,null,low_pct,medium_pct,high_pct,null_pct,medhigh,medhigh_pct,geoname,sumlevel
01000US,7,29,263,0,2.3,9.7,88.0,0.0,292,97.7,United States,US
02000US3,13,44,239,0,4.4,14.9,80.7,0.0,283,95.6,South Region,Region
02000US4,27,38,238,0,8.9,12.5,78.5,0.0,276,91.0,West Region,Region
03000US5,27,50,225,0,8.9,16.6,74.5,0.0,275,91.1,South Atlantic Division,Division
06000US4715790158,28,72,194,0,9.5,24.5,66.0,0.0,266,90.5,"District 1, Shelby County, Tennessee",County Subdiv
...,...,...,...,...,...,...,...,...,...,...,...,...
14000US39109365301,35,0,0,0,100.0,0.0,0.0,0.0,0,0.0,"Census Tract 3653.01, Miami County, Ohio",Tract
15000US290693601001,13,0,0,0,100.0,0.0,0.0,0.0,0,0.0,"Block Group 1, Census Tract 3601, Dunklin Coun...",Blk Group
15000US290693601002,14,0,0,0,100.0,0.0,0.0,0.0,0,0.0,"Block Group 2, Census Tract 3601, Dunklin Coun...",Blk Group
15000US290693601003,10,0,0,0,100.0,0.0,0.0,0.0,0,0.0,"Block Group 3, Census Tract 3601, Dunklin Coun...",Blk Group
25100US5550463,16,0,0,0,100.0,0.0,0.0,0.0,0,0.0,"Pin Oak Acres; Cherokee OTSA, OK",Tribal Subdiv

In [14]:
sum_medhigh=geo_cv['medhigh'].sum()
sum_medhigh

1030443

In [15]:
min_mh = geo_cv['medhigh'].min()
max_mh = geo_cv['medhigh'].max()
mean_mh = round(geo_cv['medhigh'].mean(),0)
std_mh=round(geo_cv['medhigh'].std(),0)
med_mh = geo_cv['medhigh'].median()
mode_mh = geo_cv['medhigh'].mode().iloc[0] 
print(min_mh, max_mh, mean_mh,std_mh,med_mh,mode_mh)

0 292 3.0 10.0 0.0 0

In [16]:
bins = [-1, 0, 74, 149, 224, 300]
labels=['0','1 to 74', '75 to 149', '150 to 224', '225 to 300']
geo_cv['medhigh_bins']=pd.cut(geo_cv['medhigh'],bins=bins,labels=labels,include_lowest=True)
geo_cv.sort_values(by='medhigh',ascending=False)

,low,medium,high,null,low_pct,medium_pct,high_pct,null_pct,medhigh,medhigh_pct,geoname,sumlevel,medhigh_bins
01000US,7,29,263,0,2.3,9.7,88.0,0.0,292,97.7,United States,US,225 to 300
02000US3,13,44,239,0,4.4,14.9,80.7,0.0,283,95.6,South Region,Region,225 to 300
02000US4,27,38,238,0,8.9,12.5,78.5,0.0,276,91.0,West Region,Region,225 to 300
03000US5,27,50,225,0,8.9,16.6,74.5,0.0,275,91.1,South Atlantic Division,Division,225 to 300
06000US4715790158,28,72,194,0,9.5,24.5,66.0,0.0,266,90.5,"District 1, Shelby County, Tennessee",County Subdiv,225 to 300
...,...,...,...,...,...,...,...,...,...,...,...,...,...
14000US39109365301,35,0,0,0,100.0,0.0,0.0,0.0,0,0.0,"Census Tract 3653.01, Miami County, Ohio",Tract,0
15000US290693601001,13,0,0,0,100.0,0.0,0.0,0.0,0,0.0,"Block Group 1, Census Tract 3601, Dunklin Coun...",Blk Group,0
15000US290693601002,14,0,0,0,100.0,0.0,0.0,0.0,0,0.0,"Block Group 2, Census Tract 3601, Dunklin Coun...",Blk Group,0
15000US290693601003,10,0,0,0,100.0,0.0,0.0,0.0,0,0.0,"Block Group 3, Census Tract 3601, Dunklin Coun...",Blk Group,0
25100US5550463,16,0,0,0,100.0,0.0,0.0,0.0,0,0.0,"Pin Oak Acres; Cherokee OTSA, OK",Tribal Subdiv,0

In [41]:
#counties_cv=geo_cv.loc[geo_cv['sumlevel']=='County']
#counties_cv.to_csv('county_counts_cv.csv')
#tracts_cv=geo_cv.loc[geo_cv['sumlevel']=='Tract']
#tracts_cv.to_csv('tracts_counts_cv.csv')

In [17]:
cnt_medhigh_bins=geo_cv.groupby('medhigh_bins',observed=True)['medhigh'].count().reset_index()
cnt_medhigh_bins['pct']=round((cnt_medhigh_bins['medhigh']/geocount)*100,1)
cnt_medhigh_bins

  medhigh_bins  medhigh   pct
0            0   252157  62.1
1      1 to 74   152281  37.5
2    75 to 149     1176   0.3
3   150 to 224      150   0.0
4   225 to 300       23   0.0

In [18]:
geo_cv.loc[geo_cv['medhigh_bins']=='225 to 300',['medhigh','medhigh_pct','geoname']].sort_values(by=['medhigh_pct','medhigh'], ascending=False).head(n=20)

,medhigh,medhigh_pct,geoname
01000US,292,97.7,United States
02000US3,283,95.6,South Region
03000US9,266,92.1,Pacific Division
03000US5,275,91.1,South Atlantic Division
02000US4,276,91.0,West Region
02000US2,264,90.8,Midwest Region
06000US4715790158,266,90.5,"District 1, Shelby County, Tennessee"
03000US7,260,89.9,West South Central Division
04000US06,262,89.7,California
03000US8,262,89.1,Mountain Division
02000US1,253,89.0,Northeast Region
04000US48,253,88.1,Texas
03000US3,251,88.0,East North Central Division
06000US4715790728,250,87.8,"District 4, Shelby County, Tennessee"
04000US12,243,87.1,Florida
03000US2,243,85.9,Middle Atlantic Division
04000US36,233,85.4,New York
40000US51445,238,85.0,"Los Angeles--Long Beach--Anaheim, CA Urbanized..."
05000US06037,231,84.6,"Los Angeles County, California"
04000US37,225,84.2,North Carolina

In [19]:
geo_cv.loc[(geo_cv['medhigh']<5)&(geo_cv['medhigh']!=0)]['medhigh'].count()

112843

In [20]:
geo_cv.loc[(geo_cv['medhigh']>=5)&(geo_cv['medhigh']!=0)]['medhigh'].count()

40787

In [21]:
cnt_medhigh_bins_subset=geo_cv.loc[geo_cv['medhigh']>=5].groupby('medhigh_bins',observed=True)['medhigh'].count().reset_index()
cnt_medhigh_bins_subset['pct']=round((cnt_medhigh_bins['medhigh']/geocount)*100,1)
cnt_medhigh_bins_subset

  medhigh_bins  medhigh   pct
0      1 to 74    39438  62.1
1    75 to 149     1176  37.5
2   150 to 224      150   0.3
3   225 to 300       23   0.0

In [22]:
cnt_cv_sumlevs=geo_cv.groupby(['medhigh_bins','sumlevel'],observed=True)['medhigh'].count().reset_index()
cnt_cv_sumlevs.sort_values(by=['medhigh_bins','medhigh'],ascending=False).head(n=50)

   medhigh_bins          sumlevel  medhigh
50   225 to 300          Division        7
52   225 to 300             State        5
51   225 to 300            Region        4
49   225 to 300     County Subdiv        2
54   225 to 300        Urban Area        2
47   225 to 300              CBSA        1
48   225 to 300            County        1
53   225 to 300                US        1
41   150 to 224            County       32
39   150 to 224              CBSA       31
45   150 to 224             State       28
46   150 to 224        Urban Area       26
42   150 to 224     County Subdiv       16
44   150 to 224             Place        9
40   150 to 224         Cong Dist        6
43   150 to 224          Division        2
28    75 to 149         Cong Dist      286
30    75 to 149            County      259
32    75 to 149              PUMA      146
31    75 to 149     County Subdiv      135
27    75 to 149              CBSA      106
33    75 to 149             Place       96
37    75 to 149        Urban Area       78
38    75 to 149              ZCTA       23
35    75 to 149             Tract       22
34    75 to 149             State       18
29    75 to 149         Cons City        4
36    75 to 149       Tribal Area        3
11      1 to 74         Blk Group    56971
20      1 to 74             Tract    44229
26      1 to 74              ZCTA    15958
16      1 to 74     County Subdiv    14867
18      1 to 74             Place    11135
15      1 to 74            County     2878
25      1 to 74        Urban Area     2322
17      1 to 74              PUMA     2232
12      1 to 74              CBSA      658
22      1 to 74  Tribal Blk Group      322
21      1 to 74       Tribal Area      252
24      1 to 74      Tribal Tract      209
23      1 to 74     Tribal Subdiv      167
13      1 to 74         Cong Dist       76
14      1 to 74         Cons City        4
19      1 to 74             State        1
0             0         Blk Group   163003
4             0             Tract    29391
2             0     County Subdiv    21524
3             0             Place    18270
10            0              ZCTA    17139
9             0        Urban Area     1164

In [23]:
cnt_cv_sumlevs['pct_group']=round((cnt_cv_sumlevs['medhigh']/cnt_cv_sumlevs.groupby(
    ['medhigh_bins'],observed=True)['medhigh'].transform('sum'))*100,1)
cnt_cv_sumlevs.sort_values(by=['medhigh_bins','pct_group','medhigh'],ascending=False)

   medhigh_bins          sumlevel  medhigh  pct_group
50   225 to 300          Division        7       30.4
52   225 to 300             State        5       21.7
51   225 to 300            Region        4       17.4
49   225 to 300     County Subdiv        2        8.7
54   225 to 300        Urban Area        2        8.7
47   225 to 300              CBSA        1        4.3
48   225 to 300            County        1        4.3
53   225 to 300                US        1        4.3
41   150 to 224            County       32       21.3
39   150 to 224              CBSA       31       20.7
45   150 to 224             State       28       18.7
46   150 to 224        Urban Area       26       17.3
42   150 to 224     County Subdiv       16       10.7
44   150 to 224             Place        9        6.0
40   150 to 224         Cong Dist        6        4.0
43   150 to 224          Division        2        1.3
28    75 to 149         Cong Dist      286       24.3
30    75 to 149            County      259       22.0
32    75 to 149              PUMA      146       12.4
31    75 to 149     County Subdiv      135       11.5
27    75 to 149              CBSA      106        9.0
33    75 to 149             Place       96        8.2
37    75 to 149        Urban Area       78        6.6
38    75 to 149              ZCTA       23        2.0
35    75 to 149             Tract       22        1.9
34    75 to 149             State       18        1.5
29    75 to 149         Cons City        4        0.3
36    75 to 149       Tribal Area        3        0.3
11      1 to 74         Blk Group    56971       37.4
20      1 to 74             Tract    44229       29.0
26      1 to 74              ZCTA    15958       10.5
16      1 to 74     County Subdiv    14867        9.8
18      1 to 74             Place    11135        7.3
15      1 to 74            County     2878        1.9
25      1 to 74        Urban Area     2322        1.5
17      1 to 74              PUMA     2232        1.5
12      1 to 74              CBSA      658        0.4
22      1 to 74  Tribal Blk Group      322        0.2
21      1 to 74       Tribal Area      252        0.2
24      1 to 74      Tribal Tract      209        0.1
23      1 to 74     Tribal Subdiv      167        0.1
13      1 to 74         Cong Dist       76        0.0
14      1 to 74         Cons City        4        0.0
19      1 to 74             State        1        0.0
0             0         Blk Group   163003       64.6
4             0             Tract    29391       11.7
2             0     County Subdiv    21524        8.5
3             0             Place    18270        7.2
10            0              ZCTA    17139        6.8
9             0        Urban Area     1164        0.5
6             0  Tribal Blk Group      593        0.2
5             0       Tribal Area      438        0.2
7             0     Tribal Subdiv      313        0.1
8             0      Tribal Tract      272        0.1
1             0            County       50        0.0